### ISSUE TITLE
Nextcloud suddenly stopped working

### ISSUE THREAD

**Issue by dextercarrasco** [nextcloud/nextcloud-snap#1056]
My nextcloud setup has been working fine for months now. Just last week, I noticed that it is not uploading my photos.
I checked my server and issuing command ```sudo nextcloud.occ app:list``` results to
```
An unhandled exception has been thrown:
RuntimeException: Could not get appdata folder in /snap/nextcloud/13968/htdocs/lib/private/Files/AppData/AppData.php:86
Stack trace:
#0 /snap/nextcloud/13968/htdocs/lib/private/Files/AppData/AppData.php(107): OC\Files\AppData\AppData->getAppDataFolder()
#1 /snap/nextcloud/13968/htdocs/lib/private/Template/IconsCacher.php(78): OC\Files\AppData\AppData->getFolder('icons')
#2 [internal function]: OC\Template\IconsCacher->__construct(Object(OC\Log), Object(OC\Files\AppData\Factory), Object(OC\URLGenerator), Object(OC\AppFramework\Utility\TimeFactory))
#3 /snap/nextcloud/13968/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(81): ReflectionClass->newInstanceArgs(Array)
#4 /snap/nextcloud/13968/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(98): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#5 /snap/nextcloud/13968/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Template\\Ico...')
#6 /snap/nextcloud/13968/htdocs/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Template\\Ico...')
#7 /snap/nextcloud/13968/htdocs/lib/private/Server.php(980): OC\ServerContainer->query('OC\\Template\\Ico...')
#8 /snap/nextcloud/13968/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#9 /snap/nextcloud/13968/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\Template\\SCS...')
#10 /snap/nextcloud/13968/htdocs/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Template\\SCS...')
#11 /snap/nextcloud/13968/htdocs/lib/private/Repair.php(148): OC\ServerContainer->query('OC\\Template\\SCS...')
#12 /snap/nextcloud/13968/htdocs/core/register_command.php(143): OC\Repair::getRepairSteps()
#13 /snap/nextcloud/13968/htdocs/lib/private/Console/Application.php(118): require_once('/snap/nextcloud...')
#14 /snap/nextcloud/13968/htdocs/console.php(95): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /snap/nextcloud/13968/htdocs/occ(11): require_once('/snap/nextcloud...')
#16 {main}
```

I have executed the following commands just in case you need them
```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

~$ snap info core
name:      core
summary:   snapd runtime environment
publisher: Canonical✓
contact:   snaps@canonical.com
license:   unset
description: |
  The core runtime environment for snapd
type:         core
snap-id:      99T7MUlRhtI3U0QFgl5mXXESAiSwt776
tracking:     stable
refresh-date: 11 days ago, at 03:19 +08
channels:
  stable:    16-2.39.3                    2019-06-27 (7270) 92MB -
  candidate: 16-2.39.3                    2019-06-25 (7270) 92MB -
  beta:      16-2.40~pre1                 2019-07-02 (7343) 92MB -
  edge:      16-2.40~pre1+git1391.d09d311 2019-07-09 (7371) 92MB -
installed:   16-2.39.3                               (7270) 92MB core

~$ snap list
Name       Version      Rev    Tracking  Publisher   Notes
core       16-2.39.3    7270   stable    canonical✓  core
lxd        3.14         11098  stable/…  canonical✓  -
nextcloud  15.0.8snap3  13968  stable    nextcloud✓  -

~$ snap changes
ID   Status  Spawn               Ready               Summary
61   Done    today at 06:33 +08  today at 06:33 +08  Refresh all snaps: no updates
62   Done    today at 06:40 +08  today at 06:40 +08  Running service command

~$ snap version
snap    2.39.3
snapd   2.39.3
series  16
ubuntu  18.10
kernel  4.18.0-25-generic
```

When accessing the page, it shows
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

Am I missing anything or perhaps needed to run some commands to have the server running again?

**Comment by kyrofa** [comment]
Nextcloud tracebacks aren't very useful, I'm afraid. I'm not sure why it's complaining about your appdata folder. Can I see the output of the following command, please?

    $ sudo nextcloud.occ config:list

**Comment by kyrofa** [comment]
Closing due to inactivity.

**Comment by pravynandas** [comment]
In my case the issue caused by a non-default data directory configured in config.php but after switching back to default it worked as expected.

**Comment by kyrofa** [comment]
@pravynandas check your `snap connections`, make sure the snap's `removable-media` interface is still connected.

**Comment by pravynandas** [comment]
Thanks @kyrofa , I was mounting my harddisk on home directory rather than /media or /mnt hence it failed. After mounting it on /media the service started without the said error
