### ISSUE TITLE
snap refresh, Upgrade to 16.05 -- Exception caused by Group folder App --

### ISSUE THREAD

**Issue by scubamuc** [nextcloud/nextcloud-snap#1126]
#### Describe the bug
`nextcloud.occ files:scan --all` experiences Exception error

#### To Reproduce
1. Install **Group folder** App in Nextcloud-snap 16.05
2. In OS open Cli and enter command `$ sudo nextcloud.occ files:scan --all`
3. See output

#### Expected behavior
`nextcloud.occ files:scan --all` should be completed without errors

#### Workaround
1. deaktivate **Group folders** App
2. In OS open Cli and enter command `$ sudo nextcloud.occ files:scan --all`
3. See output -- exception has gone away, `files:scan` is good

#### OS/snapd/snap version
Ubuntu 16.04 LTS -- Nextcloud-snap upgraded from 15.0.11 to 16.05 via snap refresh nextcloud stable

Name       Version      Rev    Tracking  Publisher   Notes
nextcloud  16.0.5snap1  16232  stable    nextcloud✓  -

snap    2.41
snapd   2.41
series  16
ubuntu  16.04
kernel  4.15.0-64-generic

#### Logs
Stacktrace from Cli:

```
An unhandled exception has been thrown:
TypeError: basename() expects parameter 1 to be string, null given in /snap/nextcloud/16232/htdocs/apps/workflowengine/lib/Check/FileName.php:62
Stack trace:
#0 /snap/nextcloud/16232/htdocs/apps/workflowengine/lib/Check/FileName.php(62): basename(NULL)
#1 /snap/nextcloud/16232/htdocs/apps/workflowengine/lib/Check/AbstractStringCheck.php(63): OCA\WorkflowEngine\Check\FileName->getActualValue()
#2 /snap/nextcloud/16232/htdocs/apps/workflowengine/lib/Manager.php(123): OCA\WorkflowEngine\Check\AbstractStringCheck->executeCheck('is', '.bak')
#3 /snap/nextcloud/16232/htdocs/apps/workflowengine/lib/Manager.php(94): OCA\WorkflowEngine\Manager->check(Array)
#4 /var/snap/nextcloud/16232/nextcloud/extra-apps/files_automatedtagging/lib/Operation.php(73): OCA\WorkflowEngine\Manager->getMatchingOperations('OCA\\FilesAutoma...', false)
#5 /var/snap/nextcloud/16232/nextcloud/extra-apps/files_automatedtagging/lib/CacheListener.php(45): OCA\FilesAutomatedTagging\Operation->checkOperations(Object(OCA\Files_Trashbin\Storage), 921207, '__groupfolders/...')
#6 /snap/nextcloud/16232/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php(212): OCA\FilesAutomatedTagging\CacheListener->onCacheEvent(Object(OCP\Files\Cache\CacheUpdateEvent), 'OCP\\Files\\Cache...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 /snap/nextcloud/16232/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'OCP\\Files\\Cache...', Object(OCP\Files\Cache\CacheUpdateEvent))
#8 /snap/nextcloud/16232/htdocs/lib/private/Files/Cache/Cache.php(345): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('OCP\\Files\\Cache...', Object(OCP\Files\Cache\CacheUpdateEvent))
#9 /snap/nextcloud/16232/htdocs/lib/private/Files/Cache/Wrapper/CacheJail.php(133): OC\Files\Cache\Cache->update(921207, Array)
#10 /snap/nextcloud/16232/htdocs/lib/private/Files/Cache/Wrapper/CacheWrapper.php(138): OC\Files\Cache\Wrapper\CacheJail->update(921207, Array)
#11 /var/snap/nextcloud/16232/nextcloud/extra-apps/groupfolders/lib/Mount/RootEntryCache.php(52): OC\Files\Cache\Wrapper\CacheWrapper->update(921207, Array)
#12 /snap/nextcloud/16232/htdocs/lib/private/Files/Cache/Wrapper/CacheWrapper.php(138): OCA\GroupFolders\Mount\RootEntryCache->update(921207, Array)
#13 /snap/nextcloud/16232/htdocs/lib/private/Files/Cache/Scanner.php(417): OC\Files\Cache\Wrapper\CacheWrapper->update(921207, Array)
#14 /snap/nextcloud/16232/htdocs/lib/private/Files/Cache/Scanner.php(338): OC\Files\Cache\Scanner->scanChildren('', true, 3, 921207, true)
#15 /snap/nextcloud/16232/htdocs/lib/private/Files/Utils/Scanner.php(245): OC\Files\Cache\Scanner->scan('', true, 3)
#16 /snap/nextcloud/16232/htdocs/apps/files/lib/Command/Scan.php(145): OC\Files\Utils\Scanner->scan('/ana', true, NULL)
#17 /snap/nextcloud/16232/htdocs/apps/files/lib/Command/Scan.php(201): OCA\Files\Command\Scan->scanFiles('ana', '/ana', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#18 /snap/nextcloud/16232/htdocs/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /snap/nextcloud/16232/htdocs/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /snap/nextcloud/16232/htdocs/3rdparty/symfony/console/Application.php(901): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /snap/nextcloud/16232/htdocs/3rdparty/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /snap/nextcloud/16232/htdocs/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /snap/nextcloud/16232/htdocs/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /snap/nextcloud/16232/htdocs/console.php(97): OC\Console\Application->run()
#25 /snap/nextcloud/16232/htdocs/occ(11): require_once('/snap/nextcloud...')
```

**Comment by kyrofa** [comment]
That looks an awful lot like a problem with the app, like perhaps it doesn't support NC16.

**Comment by scubamuc** [comment]
Thanks @kyrofa... I'll wait for an Update before reinstalling the App.
