### ISSUE TITLE
[Backup/Import] Importing sometimes succeeds, but even on succession, failure.

### ISSUE THREAD

**Issue by jtagcat** [nextcloud/nextcloud-snap#1227]
#### Describe the bug
A clear and concise description of the bug.
`nextcloud.export` ran successfully. Also backed up certs. I still have the source server available.
I did `snap save` on source and transfered the snapshot to target server. I restored the snapshot and afterwards `nextcloud.import` on target:
```
[root@k1padajada backups]# nextcloud.import ./20200120-040248                                                         
WARNING: This functionality is still experimental and under
development, use at your own risk. Note that the CLI interface is
unstable, so beware if using from within scripts.

Clearing existing non-default apps... done
Importing apps...
        116.06M 100%   30.24MB/s    0:00:03 (xfr#6647, to-chk=0/7776)   
Dropping existing database... error
ERROR 1008 (HY000) at line 1: Can't drop database 'nextcloud'; database doesn't exist
Creating new database... error
ERROR 1006 (HY000) at line 1: Can't create database 'nextcloud' (errno: 15181872)
Granting database privileges to existing user... error
ERROR 29 (HY000) at line 1: File './mysql/user.MYD' not found (Errcode: 2 - No such file or directory)
Importing database...
ERROR 1049 (42000): Unknown database 'nextcloud'
Unable to import database
Disabling maintenance mode... error
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1049] Unknown database 'nextcloud' in /snap/nextcloud/18204/htdocs/lib/private/DB/Connection.php:64
Stack trace:
#0 /snap/nextcloud/18204/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1065): OC\DB\Connection->connect()
#1 /snap/nextcloud/18204/htdocs/lib/private/DB/Connection.php(216): Doctrine\DBAL\Connection->executeUpdate('SET SESSION TRA...', Array, Array)
#2 /snap/nextcloud/18204/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(710): OC\DB\Connection->execut
eUpdate('SET SESSION TRA...')
#3 /snap/nextcloud/18204/htdocs/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(
2)
#4 /snap/nextcloud/18204/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(181): OC\DB\Connection->__c
onstruct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Com
mon\EventManager))
#5 /snap/nextcloud/18204/htdocs/lib/private/DB/ConnectionFactory.php(156): Doctrine\DBAL\DriverManager::getConnection(
Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /snap/nextcloud/18204/htdocs/lib/private/Server.php(641): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#7 /snap/nextcloud/18204/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(O
C\Server))
#8 /snap/nextcloud/18204/htdocs/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('OCP\IDBConnecti...'
)
#9 /snap/nextcloud/18204/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('
OCP\IDBConnecti...')
#10 /snap/nextcloud/18204/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleC
ontainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#11 /snap/nextcloud/18204/htdocs/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('DatabaseConnect...
')
#12 /snap/nextcloud/18204/htdocs/lib/private/Server.php(1560): OC\ServerContainer->query('DatabaseConnect...')
#13 /snap/nextcloud/18204/htdocs/lib/private/Server.php(362): OC\Server->getDatabaseConnection()
Disabling maintenance mode... error
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1049] Unknown database 'nextcloud' in /snap/nextcloud/18204/htdocs/lib/private/DB/Connection.php:64
Stack trace:
#0 /snap/nextcloud/18204/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1065): OC\DB\Connection->connect()
#1 /snap/nextcloud/18204/htdocs/lib/private/DB/Connection.php(216): Doctrine\DBAL\Connection->executeUpdate('SET SESSION TRA...', Array, Array)
#2 /snap/nextcloud/18204/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(710): OC\DB\Connection->executeUpdate('SET SESSION TRA...')
#3 /snap/nextcloud/18204/htdocs/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#4 /snap/nextcloud/18204/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(181): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#5 /snap/nextcloud/18204/htdocs/lib/private/DB/ConnectionFactory.php(156): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /snap/nextcloud/18204/htdocs/lib/private/Server.php(641): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#7 /snap/nextcloud/18204/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#8 /snap/nextcloud/18204/htdocs/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('OCP\IDBConnecti...')
#9 /snap/nextcloud/18204/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OCP\IDBConnecti...')
#10 /snap/nextcloud/18204/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#11 /snap/nextcloud/18204/htdocs/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('DatabaseConnect...')
#12 /snap/nextcloud/18204/htdocs/lib/private/Server.php(1560): OC\ServerContainer->query('DatabaseConnect...')
#13 /snap/nextcloud/18204/htdocs/lib/private/Server.php(362): OC\Server->getDatabaseConnection()
#14 /snap/nextcloud/18204/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#15 /snap/nextcloud/18204/htdocs/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('OC\Authenticati...')
#16 /snap/nextcloud/18204/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(68): OC\ServerContainer->query('OC\Authenticati...')
#17 /snap/nextcloud/18204/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(98): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#18 /snap/nextcloud/18204/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OC\Authenticati...')
#19 /snap/nextcloud/18204/htdocs/lib/private/ServerContainer.php(150): OC\AppFramework\Utility\SimpleContainer->query('OC\Authenticati...')
#20 /snap/nextcloud/18204/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(68): OC\ServerContainer->query('OC\Authenticati...')
#21 /snap/nextcloud/18204/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(98): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#22 /snap/nextcloud/18204/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OC\Authenticati...')
#23 /snap/nextcloud/18204/htdocs/lib/private/ServerContainer.php(150): OC\AppFramework\Utility\SimpleContainer->query('OC\Authenticati...')
#24 /snap/nextcloud/18204/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OC\Authenticati...')
#25 /snap/nextcloud/18204/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#26 /snap/nextcloud/18204/htdocs/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('OC\Authenticati...')
#27 /snap/nextcloud/18204/htdocs/lib/private/Server.php(374): OC\ServerContainer->query('OC\Authenticati...')
#28 /snap/nextcloud/18204/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#29 /snap/nextcloud/18204/htdocs/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('OC\User\Session')
#30 /snap/nextcloud/18204/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OC\User\Session')
#31 /snap/nextcloud/18204/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#32 /snap/nextcloud/18204/htdocs/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('UserSession')
```
I removed all snapshots and nextcloud, reinstalled nextcloud and right after installing tried to import again:
```
[root@k1padajada common]# nextcloud.import /var/snap/nextcloud/common/backups/20200120-040248/                        
WARNING: This functionality is still experimental and under
development, use at your own risk. Note that the CLI interface is

Clearing existing non-default apps... done
Importing apps...
        116.06M 100%   29.70MB/s    0:00:03 (xfr#6647, to-chk=0/7776)   
Dropping existing database... done
Creating new database... done
Granting database privileges to existing user... done
Importing database...
Importing config...
Clearing existing data... done
Importing data...
          3.20G 100%   54.22MB/s    0:00:56 (xfr#4352, to-chk=0/5427)   
Disabling maintenance mode... done
```
To my suprise it 'worked'. Now I restored the certs and chowned them to root.
I tried restarting, but still HSTS warnings and behind HSTS there is a 404 page.
I also tried to run `nextcloud.enable-https lets-encrypt`, but it resulted in `Timeout after connect (your server may be slow or overloaded)`.
#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:
    $ snap list nextcloud (same on both)
Name       Version      Rev    Tracking  Publisher   Notes
nextcloud  16.0.7snap2  18204  stable    nextcloud✓  -
    $ snap version
**Source** (Ubuntu 18.04):
snap    2.42.5
snapd   2.42.5
series  16
ubuntu  18.04
kernel  4.15.0-74-generic

**Target** (CentOS 7):
snap    2.42.2-1.el7
snapd   2.42.2-1.el7
series  16
centos  7
kernel  3.10.0-1062.9.1.el7.x86_64

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).
https://sh.c7.ee/DD9BG/source.log
https://sh.c7.ee/Rpq7G/target.log

**Comment by jtagcat** [comment]
migrated from snap to docker a long while ago
