### ISSUE TITLE
Update to v20 leaves some previously enabled apps disabled

### ISSUE THREAD

**Issue by derhagen** [nextcloud/nextcloud-snap#1529]
#### Describe the bug
Before the update, we had Calendar and Group folders installed and enabled. After the automatic update, they were unexpectedly disabled. All the other apps remained enabled, as they are supposed to be.

Also there was an available update for the Email app. I thought there was a process in place that updates all the app automatically after a snap update. Apparently, it didn't work this time.

The problem was easily fixable by activating the apps again without any problem, but it might show a flaw in the update logic.

#### To Reproduce
Sorry, I have no time to reproduce this on a separate machine. But I guess installing v19, installing Email, Group folders and Calendar, then updating to v20 should reproduce the problem.

#### Expected behavior
All previously installed apps should continue to be enabled and be updated to their latest version.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud
```
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.1snap1  24051  latest/stable  nextcloud✓  -
```
and:

    $ snap version
```
snap    2.47.1
snapd   2.47.1
series  16
ubuntu  18.04
kernel  4.15.0-122-generic
```

**Comment by kyrofa** [comment]
I suspect this is a duplicate of #1527, what do you think?

**Comment by derhagen** [comment]
Yes, indeed, I find the same exception in my logs. Sorry for that!

Should we report this to the Mail app maintainers?

Still, I wonder why a failed update of a single app disrupts the whole update process and affects other apps. Without knowing any details, could a try/catch-block help avoid this behaviour?

```
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: An unhandled exception has been thrown:
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: Error: Class 'OCA\Mail\AppInfo\BootstrapSingleton' not found in /var/snap/nextcloud/24051/nextcloud/extra-apps/mail/lib/AppInfo/Application.php:35
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: Stack trace:
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #0 /snap/nextcloud/24051/htdocs/lib/private/ServerContainer.php(108): OCA\Mail\AppInfo\Application->__construct()
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #1 /snap/nextcloud/24051/htdocs/lib/private/ServerContainer.php(171): OC\ServerContainer->getAppContainer('mail', 'Mail')
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #2 /snap/nextcloud/24051/htdocs/lib/private/ServerContainer.php(138): OC\ServerContainer->getAppContainerForService('OCA\\Mail\\Migrat...')
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #3 /snap/nextcloud/24051/htdocs/lib/private/DB/MigrationService.php(444): OC\ServerContainer->query('OCA\\Mail\\Migrat...')
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #4 /snap/nextcloud/24051/htdocs/lib/private/DB/MigrationService.php(468): OC\DB\MigrationService->createInstance('1050Date2020062...')
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #5 /snap/nextcloud/24051/htdocs/lib/private/DB/MigrationService.php(414): OC\DB\MigrationService->executeStep('1050Date2020062...', false)
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #6 /snap/nextcloud/24051/htdocs/lib/private/legacy/OC_App.php(976): OC\DB\MigrationService->migrate()
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #7 /snap/nextcloud/24051/htdocs/lib/private/Installer.php(206): OC_App::updateApp('mail')
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #8 /snap/nextcloud/24051/htdocs/lib/private/Updater.php(452): OC\Installer->updateAppstoreApp('mail')
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #9 /snap/nextcloud/24051/htdocs/lib/private/Updater.php(260): OC\Updater->upgradeAppStoreApps(Array)
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #10 /snap/nextcloud/24051/htdocs/lib/private/Updater.php(130): OC\Updater->doUpgrade('20.0.1.1', '19.0.4.2')
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #11 /snap/nextcloud/24051/htdocs/core/Command/Upgrade.php(255): OC\Updater->upgrade()
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #12 /snap/nextcloud/24051/htdocs/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #13 /snap/nextcloud/24051/htdocs/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #14 /snap/nextcloud/24051/htdocs/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #15 /snap/nextcloud/24051/htdocs/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #16 /snap/nextcloud/24051/htdocs/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #17 /snap/nextcloud/24051/htdocs/console.php(100): OC\Console\Application->run()
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #18 /snap/nextcloud/24051/htdocs/occ(11): require_once('/snap/nextcloud...')
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: #19 {main}Unable to upgrade Nextcloud. Will try again.
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: Disabling maintenance mode...
Oct 27 14:14:30 ubuntu-2gb-nbg1-1 nextcloud.apache[20619]: done
```

**Comment by kyrofa** [comment]
> Should we report this to the Mail app maintainers?

Yes, please!

> Still, I wonder why a failed update of a single app disrupts the whole update process and affects other apps. Without knowing any details, could a try/catch-block help avoid this behaviour?

Yeah you'd think the upgrade process could just disable that app and forge ahead with the rest, but in this instance we're just users of Nextcloud's existing upgrade functionality, so we'll need to log an issue upstream to get anywhere with that.
