### ISSUE TITLE
renewal of letsencrypt certificate does not seem to work

### ISSUE THREAD

**Issue by jlicher** [nextcloud/nextcloud-snap#159]
the automatic renewal of the letsencrypt certificate does not seem to work. I get informations that the certificate will expire in a few days. Some users at the forum reports the same. the wiki says 

> The certificates will automatically be kept up-to-date.

I this realy true?

**Comment by kyrofa** [comment]
Indeed that statement should be true. Can I please have the following information?

1. How did you generate the certificate (e.g. what parameters did you use for `nextcloud.enable-https`)?
2. What is the output of `journalctl -u snap.nextcloud.renew-certs.service`?

**Comment by jlicher** [comment]
I did it like mentioned in the wiki

`$ sudo nextcloud.enable-https -d`

followed by

`sudo nextcloud.enable-https`

which worked like a charm.

The output of is
`journalctl -u snap.nextcloud.renew-certs.service
-- No entries --`

**Comment by kyrofa** [comment]
Interesting. How about `systemctl status snap.nextcloud.renew-certs.service` ?

**Comment by jlicher** [comment]
```
systemctl status snap.nextcloud.renew-certs.service
● snap.nextcloud.renew-certs.service - Service for snap application nextcloud.re
   Loaded: loaded (/etc/systemd/system/snap.nextcloud.renew-certs.service; enabl
   Active: active (running) since Sat 2016-12-10 21:59:53 UTC; 3 weeks 3 days ag
 Main PID: 6278 (renew-certs)
   Memory: 16.0M
      CPU: 5min 46.557s
   CGroup: /system.slice/snap.nextcloud.renew-certs.service
           ├─ 6278 /bin/sh /snap/nextcloud/389/bin/renew-certs
           └─21086 sleep 1d

Warning: Journal has been rotated since unit was started. Log output is incomple

But I found the following in the logfiles

```
2017-01-03 22:06:02,738:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot/auth_handler.py"
, line 112, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot_nextcloud_plugin
/webroot.py", line 74, in perform
    self._set_webroots(achalls)
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot_nextcloud_plugin
/webroot.py", line 86, in _set_webroots
    self.conf("map").setdefault(achall.domain, webroot_path)
AttributeError: 'str' object has no attribute 'setdefault'

2017-01-03 22:06:02,739:DEBUG:certbot.error_handler:Calling registered functions
2017-01-03 22:06:02,740:INFO:certbot.auth_handler:Cleaning up challenges
2017-01-03 22:06:02,742:WARNING:certbot.renewal:Attempting to renew cert from /v
ar/snap/nextcloud/current/certs/certbot/config/renewal/cloud.denketage.de.conf p
roduced an unexpected error: 'str' object has no attribute 'setdefault'. Skippin
g.
```

**Comment by kyrofa** [comment]
Well that doesn't look good. Do me a favor: Run `sudo systemctl restart snap.nextcloud.renew-certs.service` and verify that it fails again. Then paste in the contents of `/var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log`.

**Comment by jlicher** [comment]
It fails again. As is dont kow ig there are some informations ins the log, which should not seen by everyone, the last part of the contents of letsencrypt.log is


```
2017-01-04 18:40:08,590:INFO:certbot.auth_handler:Performing the following challenges:
2017-01-04 18:40:08,592:INFO:certbot.auth_handler:http-01 challenge for cloud.denketage.de
2017-01-04 18:40:08,594:INFO:certbot_nextcloud_plugin.webroot:Using the webroot path ] for all unmatched domains.
2017-01-04 18:40:08,599:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot/auth_handler.py", line 112, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot_nextcloud_plugin/webroot.py", line 74, in perform
    self._set_webroots(achalls)
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot_nextcloud_plugin/webroot.py", line 86, in _set_webroots
    self.conf("map").setdefault(achall.domain, webroot_path)
AttributeError: 'str' object has no attribute 'setdefault'

2017-01-04 18:40:08,600:DEBUG:certbot.error_handler:Calling registered functions
2017-01-04 18:40:08,601:INFO:certbot.auth_handler:Cleaning up challenges
2017-01-04 18:40:08,602:WARNING:certbot.renewal:Attempting to renew cert from /var/snap/nextcloud/current/certs/certbot/config/renewal/cloud.denketage.de.conf produced an unexpected error: 'str' object has no attribute 'setdefault'. Skipping.
2017-01-04 18:40:08,610:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot/renewal.py", line 348, in renew_all_lineages
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot/main.py", line 563, in obtain_cert
    action, _ = _auth_from_domains(le_client, config, domains, lineage)
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot/main.py", line 96, in _auth_from_domains
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot/renewal.py", line 238, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot/client.py", line 253, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot/auth_handler.py", line 74, in get_authorizations
    resp = self._solve_challenges()
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot/auth_handler.py", line 112, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot_nextcloud_plugin/webroot.py", line 74, in perform
    self._set_webroots(achalls)
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot_nextcloud_plugin/webroot.py", line 86, in _set_webroots
    self.conf("map").setdefault(achall.domain, webroot_path)
AttributeError: 'str' object has no attribute 'setdefault'

2017-01-04 18:40:08,633:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/snap/nextcloud/389/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot/main.py", line 592, in renew
    renewal.renew_all_lineages(config)
  File "/snap/nextcloud/389/lib/python2.7/site-packages/certbot/renewal.py", line 365, in renew_all_lineages
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)
```

**Comment by kyrofa** [comment]
Alright. I neglected to depend on a specific certbot version, and it appears the plugin API has changed slightly. I suspect that's the issue, and will fix it right away.

As a workaround, have you tried simply running `sudo nextcloud.enable-https` again? It seems that part of the plugin still works, and it'll simply obtain a new certificate.

**Comment by jlicher** [comment]
As the certificate ist still valid for a few days, i can check whether the fix works or not. So just tell me what i have to do when it is fixed.

**Comment by kyrofa** [comment]
Alright, but FYI the fix will be included in the next release, which will be Nextcloud 11.

**Comment by kyrofa** [comment]
This bug should be fixed in the next release, v11.0.0snap1. It's [currently building](https://code.launchpad.net/~nextcloud-snappy-dev/+snap/nextcloud), and when it's completed you should get an automatic update within 8 hours. When that happens, the renewal should happen automatically.

If you want it sooner, keep an eye on the builds and run `sudo snap refresh` when they've completed.

**Comment by kyrofa** [comment]
Note that the builds have all completed.

**Comment by jlicher** [comment]
Unfortunately it does not seem to work. After snap refresh i get another errormessage in lentsencypt.log

```
2017-01-06 07:57:23,847:DEBUG:certbot.main:Root logging level set at 20
2017-01-06 07:57:23,865:INFO:certbot.main:Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
2017-01-06 07:57:23,889:DEBUG:certbot.main:certbot version: 0.9.3
2017-01-06 07:57:23,891:DEBUG:certbot.main:Arguments: ['--text', '--config-dir', '/var/snap/nextcloud/current/certs/certbot/config', '--work-dir', '/var/snap/nextcloud/current/certs/certbot/work
', '--logs-dir', '/var/snap/nextcloud/current/certs/certbot/logs']
2017-01-06 07:57:23,898:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone,PluginEntryPoint
#nextcloud:webroot)
2017-01-06 07:57:23,960:WARNING:certbot.renewal:Renewal configuration file /var/snap/nextcloud/current/certs/certbot/config/renewal/cloud.denketage.de.conf produced an unexpected error: 'Namespa
ce' object has no attribute 'nextcloud:webroot_map'. Skipping.
2017-01-06 07:57:23,966:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/snap/nextcloud/529/lib/python2.7/site-packages/certbot/renewal.py", line 330, in renew_all_lineages
    renewal_candidate = _reconstitute(lineage_config, renewal_file)
  File "/snap/nextcloud/529/lib/python2.7/site-packages/certbot/renewal.py", line 81, in _reconstitute
    _restore_plugin_configs(config, renewalparams)
  File "/snap/nextcloud/529/lib/python2.7/site-packages/certbot/renewal.py", line 148, in _restore_plugin_configs
    if config_item.startswith(plugin_prefix + "_") and not cli.set_by_cli(config_item):
  File "/snap/nextcloud/529/lib/python2.7/site-packages/certbot/cli.py", line 206, in set_by_cli
    if not isinstance(getattr(detector, var), _Default):
AttributeError: 'Namespace' object has no attribute 'nextcloud:webroot_map'

2017-01-06 07:57:23,970:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/snap/nextcloud/529/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/snap/nextcloud/529/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/snap/nextcloud/529/lib/python2.7/site-packages/certbot/main.py", line 592, in renew
    renewal.renew_all_lineages(config)
  File "/snap/nextcloud/529/lib/python2.7/site-packages/certbot/renewal.py", line 365, in renew_all_lineages
    len(renew_failures), len(parse_failures)))
Error: 0 renew failure(s), 1 parse failure(s)
```

**Comment by jlicher** [comment]
In the conf file fpr renewal i find an entry like this:

[[nextcloud:webroot_map]]

I think this is not a valid attribute. Right?

**Comment by kyrofa** [comment]
Ah good catch-- this is difficult to test correctly! I'll have another fix out shortly.

**Comment by kyrofa** [comment]
Alright let's try to kill this thing again. I took a lot of time hacking it to try and test this exact scenario, hopefully I got it this time. The [builds are running](https://code.launchpad.net/~nextcloud-snappy-dev/+snap/nextcloud) and you should get them soon. Again, the renewal should happen automatically.

**Comment by kyrofa** [comment]
Note that the builds have all completed.

**Comment by jlicher** [comment]
Renewal works now. Thank you for the fast solution.

**Comment by kyrofa** [comment]
@jlicher thank you for being willing to test the fix!

**Comment by sammish** [comment]
@jlicher how done renewal in letsencrypt certificate  can u send me steps

**Comment by pachulo** [comment]
@sammish commenting closed issues is discouraged, but the certificates will automatically be kept up-to-date.

**Comment by sammish** [comment]
ok thanks
