### ISSUE TITLE
letsencrypt certbot auto renewal errors

### ISSUE THREAD

**Issue by mr-bryn** [nextcloud/nextcloud-snap#1759]
Hi,

I've been running NextCloud Snap for years and it's great!

The other day I got an email from Let's Encrypt to say my certificate would expire soon!

Within /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log I found numerous python errors and tracebacks (log attached below).

Not much changes on this system aside from installing recommended updates, and of course the snap updates itself.

Is this a known issue with the snap, nextcloud, certbot...?
How can I go about renewing the certificate?

Thanks in advance!

#### To Reproduce
1. Enable HTTPS with the letsencrypt option - "nextcloud.enable-https lets-encrypt"

#### Expected behavior
The letsencrypt certificate auto-renews in the background

#### OS/snapd/snap version
What OS and version are you running?
`Debian 10`

    $ snap list nextcloud
`nextcloud  21.0.1snap2  28088  latest/stable  nextcloud✓`

    $ snap version
```
snap    2.50.1
snapd   2.50.1
series  16
debian  10
kernel  4.19.0-16-amd64
```

#### Logs

```
2021-06-08 16:02:59,920:INFO:certbot.auth_handler:Performing the following challenges:
2021-06-08 16:02:59,920:INFO:certbot.auth_handler:http-01 challenge for site.com
2021-06-08 16:02:59,921:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/auth_handler.py", line 69, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 81, in perform
    self._set_webroots(achalls)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 99, in _set_webroots
    known_webroots)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 120, in _prompt_for_webroot
    webroot = self._prompt_for_new_webroot(domain, True)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 144, in _prompt_for_new_webroot
    force_interactive=True)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/display/ops.py", line 371, in validated_directory
    validator, *args, **kwargs)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/display/ops.py", line 328, in _get_validated
    code, raw = method(message, default=default, **kwargs)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/display/util.py", line 583, in directory_select
    return self.input(message, default, cli_flag)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/display/util.py", line 524, in input
    self._interaction_fail(message, cli_flag)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/display/util.py", line 469, in _interaction_fail
    raise errors.MissingCommandlineFlag(msg)
MissingCommandlineFlag: Missing command line flag or config entry for this setting:
Input the webroot for site.com:

2021-06-08 16:02:59,921:DEBUG:certbot.error_handler:Calling registered functions
2021-06-08 16:02:59,921:INFO:certbot.auth_handler:Cleaning up challenges
2021-06-08 16:02:59,922:DEBUG:certbot.plugins.webroot:All challenges cleaned up
2021-06-08 16:02:59,922:WARNING:certbot.renewal:Attempting to renew cert (site.com) from /var/snap/nextcloud/current/certs/certbot/config/renewal/site.com.conf produced an unexpected error: Missing command line flag or config entry for this setting:
Input the webroot for site.com:. Skipping.
2021-06-08 16:02:59,923:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/renewal.py", line 450, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/main.py", line 1192, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/main.py", line 115, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/renewal.py", line 308, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/client.py", line 349, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/client.py", line 385, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/auth_handler.py", line 69, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 81, in perform
    self._set_webroots(achalls)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 99, in _set_webroots
    known_webroots)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 120, in _prompt_for_webroot
    webroot = self._prompt_for_new_webroot(domain, True)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 144, in _prompt_for_new_webroot
    force_interactive=True)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/display/ops.py", line 371, in validated_directory
    validator, *args, **kwargs)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/display/ops.py", line 328, in _get_validated
    code, raw = method(message, default=default, **kwargs)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/display/util.py", line 583, in directory_select
    return self.input(message, default, cli_flag)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/display/util.py", line 524, in input
    self._interaction_fail(message, cli_flag)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/display/util.py", line 469, in _interaction_fail
    raise errors.MissingCommandlineFlag(msg)
MissingCommandlineFlag: Missing command line flag or config entry for this setting:
Input the webroot for site.com:

2021-06-08 16:02:59,923:ERROR:certbot.renewal:All renewal attempts failed. The following certs could not be renewed:
2021-06-08 16:02:59,923:ERROR:certbot.renewal:  /var/snap/nextcloud/current/certs/certbot/config/live/site.com/fullchain.pem (failure)
2021-06-08 16:02:59,924:INFO:certbot.hooks:Running post-hook command: restart-apache
2021-06-08 16:03:01,058:INFO:certbot.hooks:Output from post-hook command restart-apache:
Restarting apache... done

2021-06-08 16:03:01,058:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/snap/nextcloud/28088/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/main.py", line 1271, in renew
    renewal.handle_renewal_request(config)
  File "/snap/nextcloud/28088/lib/python2.7/site-packages/certbot/renewal.py", line 475, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)

```

**Comment by kyrofa** [comment]
Huh, mine is still puttering along without issue, let's dig into this a little. Can I please see the output of `sudo snap logs -n 100 nextcloud.renew-certs`? Feel free to mask domain names as you see fit.

**Comment by kyrofa** [comment]
Alright, can I also see `/var/snap/nextcloud/current/certs/certbot/config/renewal/site.com.conf`, please?

**Comment by mr-bryn** [comment]
please see below. let me know if I've inadvertantly redacted something useful!

```
# renew_before_expiry = 30 days
version = 0.33.1
archive_dir = /var/snap/nextcloud/current/certs/certbot/config/archive/site.com
cert = /var/snap/nextcloud/current/certs/certbot/config/live/site.com/cert.pem
privkey = /var/snap/nextcloud/current/certs/certbot/config/live/site.com/privkey.pem
chain = /var/snap/nextcloud/current/certs/certbot/config/live/site.com/chain.pem
fullchain = /var/snap/nextcloud/current/certs/certbot/config/live/site.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = xxxxx
work_dir = /var/snap/nextcloud/current/certs/certbot/work
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = webroot
logs_dir = /var/snap/nextcloud/current/certs/certbot/logs
rsa_key_size = 4096
config_dir = /var/snap/nextcloud/current/certs/certbot/config
webroot_path = /var/snap/nextcloud/current/certs/certbot,
[[webroot_map]]

```

**Comment by kyrofa** [comment]
Your `[[webroot_map]]`, is it actually empty like that? You didn't just redact it?

**Comment by mr-bryn** [comment]
yes. I just double-checked on the server.

The last line in that conf file is `[[webroot_map]]` with nothing further

**Comment by kyrofa** [comment]
Okay so this config looks... odd. I haven't shipped a certbot update for a significant amount of time, so I can't really explain what's going on here to be honest. I assume you haven't been running another version of certbot with this config, outside of the snap somehow? Throwing darts, here :) .

Regardless of why this happened, let's get you fixed. Try making the webroot_map section look like this (unredact, obviously):

```
[[webroot_map]]
site.com = /var/snap/nextcloud/current/certs/certbot
```

**Comment by mr-bryn** [comment]
Well that fixed it! If I did somehow break it by running something outside of the snap I expect it'll break again, but the regualr certbot package isn't installed on this system, so hopefully it'll keep working!

For now the log reports the certificate renewal succeeded, and a quick check of the site now shows

```
Valid from | Tue, 08 Jun 2021 23:07:45 UTC
Valid until | Mon, 06 Sep 2021 23:07:45 UTC
```
Thanks @kyrofa for your help and work on this project!

**Comment by adrianvg** [comment]
Out of curiosity I checked my install too.
Seems like I have the same problem.

However, no certs have been invalidated the last six months. 
Maybe this works anyway, and is an effect because I run nextcloud.snap behind a reverse proxy manager that handles the certs itself?

**Comment by kyrofa** [comment]
> Maybe this works anyway, and is an effect because I run nextcloud.snap behind a reverse proxy manager that handles the certs itself?

Yeah if you're not using the snap as an SSL terminator, you're not using those config files at all, so that makes sense.

**Comment by kyrofa** [comment]
I really just need to move away from certbot, I've been pretty significantly unhappy with it to be honest.

**Comment by adrianvg** [comment]
> I really just need to move away from certbot, I've been pretty significantly unhappy with it to be honest.

What alternatives would we have? What are your thoughts on certificates? Using it in a stand-alone kind of way, dump it altogether or something else entirely?

The case for Let's Encrypt is pretty big, being free and all. 
Generally speaking it's easy to setup and use even for hamfisted n00bs most of the time (as it was for me in the beginning), but I can see how it might be a PITA to integrate it in eg a snap from a dev angle.

BTW, is this the correct place to discuss this?
Am curious though on the Let's Encrypt-future with Nextcloud.snap given your feelings stated above!

**Comment by kyrofa** [comment]
Oh don't worry, Let's Encrypt is fantastic, I don't plan to move away from it at all. I just don't like the certbot tooling. There are several alternatives, I've been particularly interested in Apache's mod_md, for example. Whatever direction I go with that (when I have time), it will be a seamless transition from existing certs, or I won't do it at all. The end user experience in the snap won't change a bit, although it might get a smidge simpler.
