### ISSUE TITLE
FullTextSearch with ElasticSearch doesn't work on NC 21 snap

### ISSUE THREAD

**Issue by Jsalas424** [nextcloud/nextcloud-snap#1765]
#### Describe the bug
I have been successfully indexing my documents and pdf's on Nextcloud with FullTextSearch backed by ElasticSearch, after the upgrade to v21, this is broken.

#### To Reproduce
```
jon@nextcloud:~$ sudo nextcloud.occ fulltextsearch:stop
stopping all running indexes
jon@nextcloud:~$ sudo nextcloud.occ fulltextsearch:index --no-readline

Options: {"_no-readline":true}
Memory: 35 MB
┌─ Indexing  ────
│ Action: generateIndexFiles
│ Provider: Files                Account: jon
│ Document: 
│ Info: 
│ Title: 
│ Content size: 
│ Chunk:      0/0
│ Progress:      0/0
└──
┌─ Results ────
│ Result:      0/0
│ Index: 
│ Status: 
│ Message: 
│ 
│ 
└──
┌─ Errors ────
│ Error:      0/0
│ Index: 
│ Exception: 
│ Message: 
│ 
│ 
└──
An unhandled exception has been thrown:
TypeError: Return value of OCA\Files_FullTextSearch\Model\MountPoint::isGlobal() must be of the type bool, null returned in /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/Model/MountPoint.php:103
Stack trace:
#0 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/Model/MountPoint.php(175): OCA\Files_FullTextSearch\Model\MountPoint->isGlobal()
#1 [internal function]: OCA\Files_FullTextSearch\Model\MountPoint->jsonSerialize()
#2 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/TNC22Logger.php(193): json_encode(Array)
#3 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/TNC22Logger.php(178): OCA\Files_FullTextSearch\Service\GroupFoldersService->log(0, '[debug] initGro...', false, Array)
#4 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/Service/GroupFoldersService.php(133): OCA\Files_FullTextSearch\Service\GroupFoldersService->debug('[debug] initGro...', Array)
#5 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/Service/FilesService.php(379): OCA\Files_FullTextSearch\Service\GroupFoldersService->initGroupSharesForUser('jon')
#6 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/Service/FilesService.php(202): OCA\Files_FullTextSearch\Service\FilesService->initFileSystems('jon')
#7 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/Provider/FilesProvider.php(249): OCA\Files_FullTextSearch\Service\FilesService->getChunksFromUser('jon', Object(OCA\FullTextSearch\Model\IndexOptions))
#8 /var/snap/nextcloud/28088/nextcloud/extra-apps/fulltextsearch/lib/Service/IndexService.php(182): OCA\Files_FullTextSearch\Provider\FilesProvider->generateChunks('jon')
#9 /var/snap/nextcloud/28088/nextcloud/extra-apps/fulltextsearch/lib/Command/Index.php(410): OCA\FullTextSearch\Service\IndexService->indexProviderContentFromUser(Object(OCA\FullTextSearch_Elasticsearch\Platform\ElasticSearchPlatform), Object(OCA\Files_FullTextSearch\Provider\FilesProvider), 'jon', Object(OCA\FullTextSearch\Model\IndexOptions))
#10 /var/snap/nextcloud/28088/nextcloud/extra-apps/fulltextsearch/lib/Command/Index.php(273): OCA\FullTextSearch\Command\Index->indexProvider(Object(OCA\Files_FullTextSearch\Provider\FilesProvider), Object(OCA\FullTextSearch\Model\IndexOptions))
#11 /var/snap/nextcloud/28088/nextcloud/extra-apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OCA\FullTextSearch\Command\Index->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /snap/nextcloud/28088/htdocs/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/snap/nextcloud/28088/nextcloud/extra-apps/bookmarks/vendor/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/snap/nextcloud/28088/nextcloud/extra-apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FullTextSearch\Command\Index), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/snap/nextcloud/28088/nextcloud/extra-apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /snap/nextcloud/28088/htdocs/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /snap/nextcloud/28088/htdocs/console.php(100): OC\Console\Application->run()
#18 /snap/nextcloud/28088/htdocs/occ(11): require_once('/snap/nextcloud...')
```
#### Expected behavior
If you run index again it say's it's running but no new files get processed. 

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud

```
jon@nextcloud:~$ snap list
Name       Version      Rev    Tracking         Publisher   Notes
core18     20210507     2066   latest/stable    canonical✓  base
lxd        4.15         20684  latest/stable/…  canonical✓  -
nextcloud  21.0.1snap2  28088  latest/stable    nextcloud✓  -
snapd      2.50.1       12057  latest/stable    canonical✓  snapd
```

and:

    $ snap version

```
jon@nextcloud:~$ snap version
snap    2.50.1
snapd   2.50.1
series  16
ubuntu  20.04
kernel  5.4.0-74-generic
```

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by Omaha2002** [comment]
Same issue after reinstalling Fulltextsearch apps, stop, reset and index.

**Comment by Jsalas424** [comment]
> Same issue after reinstalling Fulltextsearch apps, stop, reset and index.

I wasn't certain if you were suggesting to stop, reset, and restart the index service as a fix, so I tried it anyways. It didn't work.

```
jon@nextcloud:~$ sudo nextcloud.occ fulltextsearch:stop
[sudo] password for jon: 
stopping all running indexes
jon@nextcloud:~$ sudo nextcloud.occ fulltextsearch:reset
reset.
jon@nextcloud:~$ sudo nextcloud.occ fulltextsearch:index --no-readline






Options: {"_no-readline":true}
Memory: 
┌─ Indexing  ────
│ Action: 
│ Provider:                      Account: 
Options: {"_no-readline":true}
Memory: 35 MB
┌─ Indexing  ────
│ Action: generateIndexFiles
│ Provider: Files                Account: jon
│ Document: 
│ Info: 
│ Title: 
│ Content size: 
│ Chunk:      0/0
│ Progress:      0/0
└──
┌─ Results ────
│ Result:      0/0
│ Index: 
│ Status: 
│ Message: 
│ 
│ 
└──
┌─ Errors ────
│ Error:      0/0
│ Index: 
│ Exception: 
│ Message: 
│ 
│ 
└──
An unhandled exception has been thrown:
TypeError: Return value of OCA\Files_FullTextSearch\Model\MountPoint::isGlobal() must be of the type bool, null returned in /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/Model/MountPoint.php:103
Stack trace:
#0 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/Model/MountPoint.php(175): OCA\Files_FullTextSearch\Model\MountPoint->isGlobal()
#1 [internal function]: OCA\Files_FullTextSearch\Model\MountPoint->jsonSerialize()
#2 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/TNC22Logger.php(193): json_encode(Array)
#3 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/TNC22Logger.php(178): OCA\Files_FullTextSearch\Service\GroupFoldersService->log(0, '[debug] initGro...', false, Array)
#4 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/Service/GroupFoldersService.php(133): OCA\Files_FullTextSearch\Service\GroupFoldersService->debug('[debug] initGro...', Array)
#5 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/Service/FilesService.php(379): OCA\Files_FullTextSearch\Service\GroupFoldersService->initGroupSharesForUser('jon')
#6 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/Service/FilesService.php(202): OCA\Files_FullTextSearch\Service\FilesService->initFileSystems('jon')
#7 /var/snap/nextcloud/28088/nextcloud/extra-apps/files_fulltextsearch/lib/Provider/FilesProvider.php(249): OCA\Files_FullTextSearch\Service\FilesService->getChunksFromUser('jon', Object(OCA\FullTextSearch\Model\IndexOptions))
#8 /var/snap/nextcloud/28088/nextcloud/extra-apps/fulltextsearch/lib/Service/IndexService.php(182): OCA\Files_FullTextSearch\Provider\FilesProvider->generateChunks('jon')
#9 /var/snap/nextcloud/28088/nextcloud/extra-apps/fulltextsearch/lib/Command/Index.php(410): OCA\FullTextSearch\Service\IndexService->indexProviderContentFromUser(Object(OCA\FullTextSearch_Elasticsearch\Platform\ElasticSearchPlatform), Object(OCA\Files_FullTextSearch\Provider\FilesProvider), 'jon', Object(OCA\FullTextSearch\Model\IndexOptions))
#10 /var/snap/nextcloud/28088/nextcloud/extra-apps/fulltextsearch/lib/Command/Index.php(273): OCA\FullTextSearch\Command\Index->indexProvider(Object(OCA\Files_FullTextSearch\Provider\FilesProvider), Object(OCA\FullTextSearch\Model\IndexOptions))
#11 /var/snap/nextcloud/28088/nextcloud/extra-apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OCA\FullTextSearch\Command\Index->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /snap/nextcloud/28088/htdocs/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/snap/nextcloud/28088/nextcloud/extra-apps/bookmarks/vendor/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/snap/nextcloud/28088/nextcloud/extra-apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FullTextSearch\Command\Index), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/snap/nextcloud/28088/nextcloud/extra-apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /snap/nextcloud/28088/htdocs/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /snap/nextcloud/28088/htdocs/console.php(100): OC\Console\Application->run()
#18 /snap/nextcloud/28088/htdocs/occ(11): require_once('/snap/nextcloud...')
```

**Comment by escribana** [comment]
A couple of minutes ago I installed FullTextSearch freshly on Nextcloud 21.0.2 stable. If I start indexing the command "sudo -u www-data php occ fulltextsearch:index" throws exactly the same errors!

Are there some news about this?

**Comment by steffeneichler** [comment]
Same problem here on Ubuntu 18.04 LTS

**Comment by escribana** [comment]
ShinjiLE's tip on https://github.com/nextcloud/files_fulltextsearch/issues/125# solved the problem: FulTextSearch is fully working, exept the logging. :-)

**Comment by Jsalas424** [comment]
Fixed by commenting out line 133 of `/var/snap/nextcloud/current/nextcloud/extra-apps/files_fulltextsearch/lib/Service/GroupFoldersService.php`
