### ISSUE TITLE
Certbot error: 'tuple' object has no attribute 'add'

### ISSUE THREAD

**Issue by vhschlenker** [nextcloud/nextcloud-snap#279]
I have the following problem with the certbot while enabling https:
```
Attempting to obtain certificates... error running certbot:

Traceback (most recent call last):
  File "/snap/nextcloud/1333/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/snap/nextcloud/1333/lib/python2.7/site-packages/certbot/main.py", line 735, in main
    args = cli.prepare_and_parse_args(plugins, cli_args)
  File "/snap/nextcloud/1333/lib/python2.7/site-packages/certbot/cli.py", line 892, in prepare_and_parse_args
    helpful.add_deprecated_argument("--agree-dev-preview", 0)
  File "/snap/nextcloud/1333/lib/python2.7/site-packages/certbot/cli.py", line 572, in add_deprecated_argument
    self.parser.add_argument, argument_name, num_args)
  File "/snap/nextcloud/1333/lib/python2.7/site-packages/certbot/util.py", line 388, in add_deprecated_argument
    configargparse.ACTION_TYPES_THAT_DONT_NEED_A_VALUE.add(ShowWarning)
AttributeError: 'tuple' object has no attribute 'add'
```
This issue is known by the certbot github and already solved: [https://github.com/certbot/certbot/issues/4648](https://github.com/certbot/certbot/issues/4648)

**Comment by kyrofa** [comment]
Confirmed, thank you for the report.

**Comment by kyrofa** [comment]
@vhschlenker, @jbdv-ife would you both please try switching to the channel given in #284 and verify that this issue is fixed?

**Comment by vhschlenker** [comment]
@kyrofa You pull request works as expected and fixes the issue, thanks for the quick response!

**Comment by kyrofa** [comment]
No problem, thanks for reporting! However, let's leave the issue open until it's actually contained in a release, or we might get a dupe.
