### ISSUE TITLE
Missing required dependency: FreeType for PHP

### ISSUE THREAD

**Issue by blkeller** [nextcloud/nextcloud-snap#418]
I attempted to try out Nextcloud 13.0.0RC1 via the snap package, but it looks like they've introduced a new required dependecy that the snap package is not providing:

![image](https://user-images.githubusercontent.com/17344566/35170545-46711f3a-fd26-11e7-877e-7ee5b3af0c90.png)

This is causing some surprisingly severe problems, such as being unable to delete user accounts from either the GUI or via `nextcloud.occ`:

```console
brett@nextcloud-test:~$ sudo snap refresh
All snaps up to date.

brett@nextcloud-test:~$ snap info nextcloud
name:      nextcloud
summary:   Nextcloud Server - A safe home for all your data
publisher: nextcloud
contact:   https://github.com/nextcloud/nextcloud-snap
description: |
  Access, share and protect your files, calendars, contacts, communication and
  more at home and in your enterprise.
snap-id: njObIbGQEaVx1H4nyWxchk1i8opy4h54
commands:
  - nextcloud.disable-https
  - nextcloud.enable-https
  - nextcloud.manual-install
  - nextcloud.mysql-client
  - nextcloud.mysqldump
  - nextcloud.occ
services:
  nextcloud.apache:         simple, enabled, active
  nextcloud.mdns-publisher: simple, enabled, active
  nextcloud.mysql:          simple, enabled, active
  nextcloud.nextcloud-cron: simple, enabled, active
  nextcloud.php-fpm:        simple, enabled, active
  nextcloud.redis-server:   simple, enabled, active
  nextcloud.renew-certs:    simple, enabled, active
tracking:                   13/candidate
installed:                  13.0.0-rc1snap1 (4781) 192MB -
refreshed:                  2018-01-15 10:33:47 -0600 CST
channels:
  stable:                   12.0.4snap1       (4371) 192MB -
  candidate:                12.0.4snap1       (4371) 192MB -
  beta:                     12.0.4snap1       (4474) 192MB -
  edge:                     master-2018-01-19 (4811) 192MB -
  11/stable:                11.0.6snap1       (4724) 191MB -
  11/candidate:             11.0.6snap1       (4724) 191MB -
  11/beta:                  11.0.6snap1       (4724) 191MB -
  11/edge:                  11-2018-01-19     (4808) 191MB -
  12/stable:                –
  12/candidate:             –
  12/beta:                  –
  12/edge:                  12-2018-01-19     (4807) 192MB -
  13/stable:                –
  13/candidate:             13.0.0-rc1snap1   (4781) 192MB -
  13/beta:                  ↑
  13/edge:                  ↑

brett@nextcloud-test:~$ sudo nextcloud.occ user:list
  - bkeller: Brett Keller
  - testuser: Test User

brett@nextcloud-test:~$ sudo nextcloud.occ user:delete testuser
An unhandled exception has been thrown:
Error: Call to undefined function OC\imagettfbbox() in /snap/nextcloud/4781/htdocs/lib/private/Avatar.php:255
Stack trace:
#0 /snap/nextcloud/4781/htdocs/lib/private/Avatar.php(176): OC\Avatar->generateAvatar('Test User', 1024)
#1 /snap/nextcloud/4781/htdocs/lib/private/Avatar.php(86): OC\Avatar->getFile(-1)
#2 /snap/nextcloud/4781/htdocs/lib/private/User/User.php(419): OC\Avatar->get(-1)
#3 /snap/nextcloud/4781/htdocs/apps/dav/lib/CardDAV/Converter.php(146): OC\User\User->getAvatarImage(-1)
#4 /snap/nextcloud/4781/htdocs/apps/dav/lib/CardDAV/Converter.php(56): OCA\DAV\CardDAV\Converter->getAvatarImage(Object(OC\User\User))
#5 /snap/nextcloud/4781/htdocs/apps/dav/lib/CardDAV/SyncService.php(276): OCA\DAV\CardDAV\Converter->createCardFromUser(Object(OC\User\User))
#6 /snap/nextcloud/4781/htdocs/apps/dav/lib/HookManager.php(124): OCA\DAV\CardDAV\SyncService->updateUser(Object(OC\User\User))
#7 /snap/nextcloud/4781/htdocs/lib/private/legacy/hook.php(106): OCA\DAV\HookManager->changeUser(Array)
#8 /snap/nextcloud/4781/htdocs/lib/private/Server.php(399): OC_Hook::emit('OC_User', 'changeUser', Array)
#9 [internal function]: OC\Server->OC\{closure}(Object(OC\User\User), 'avatar', '', NULL)
#10 /snap/nextcloud/4781/htdocs/lib/private/Hooks/EmitterTrait.php(99): call_user_func_array(Object(Closure), Array)
#11 /snap/nextcloud/4781/htdocs/lib/private/Hooks/PublicEmitter.php(36): OC\Hooks\BasicEmitter->emit('\\OC\\User', 'changeUser', Array)
#12 /snap/nextcloud/4781/htdocs/lib/private/User/User.php(456): OC\Hooks\PublicEmitter->emit('\\OC\\User', 'changeUser', Array)
#13 /snap/nextcloud/4781/htdocs/lib/private/Avatar.php(166): OC\User\User->triggerChange('avatar', '')
#14 /snap/nextcloud/4781/htdocs/lib/private/Server.php(1171): OC\Avatar->remove()
#15 [internal function]: OC\Server->OC\{closure}(Object(Symfony\Component\EventDispatcher\GenericEvent), 'OCP\\IUser::preD...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#16 /snap/nextcloud/4781/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Object(Closure), Object(Symfony\Component\EventDispatcher\GenericEvent), 'OCP\\IUser::preD...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#17 /snap/nextcloud/4781/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'OCP\\IUser::preD...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#18 /snap/nextcloud/4781/htdocs/lib/private/Server.php(369): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('OCP\\IUser::preD...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#19 [internal function]: OC\Server->OC\{closure}(Object(OC\User\User))
#20 /snap/nextcloud/4781/htdocs/lib/private/Hooks/EmitterTrait.php(99): call_user_func_array(Object(Closure), Array)
#21 /snap/nextcloud/4781/htdocs/lib/private/Hooks/PublicEmitter.php(36): OC\Hooks\BasicEmitter->emit('\\OC\\User', 'preDelete', Array)
#22 /snap/nextcloud/4781/htdocs/lib/private/User/User.php(203): OC\Hooks\PublicEmitter->emit('\\OC\\User', 'preDelete', Array)
#23 /snap/nextcloud/4781/htdocs/core/Command/User/Delete.php(64): OC\User\User->delete()
#24 /snap/nextcloud/4781/htdocs/3rdparty/symfony/console/Command/Command.php(264): OC\Core\Command\User\Delete->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /snap/nextcloud/4781/htdocs/3rdparty/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /snap/nextcloud/4781/htdocs/3rdparty/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\User\Delete), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /snap/nextcloud/4781/htdocs/3rdparty/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /snap/nextcloud/4781/htdocs/lib/private/Console/Application.php(173): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /snap/nextcloud/4781/htdocs/console.php(90): OC\Console\Application->run()
#30 /snap/nextcloud/4781/htdocs/occ(11): require_once('/snap/nextcloud...')
#31 {main}

```

Please add the missing dependency to the snap package.  Thanks!

**Comment by kyrofa** [comment]
Thanks for the detailed report! On it.

**Comment by kyrofa** [comment]
You will automatically update soon, but if you run `snap refresh nextcloud` manually you'll see an update on `13/candidate`. It's now RC2, and should have freetype enabled. Can you verify?

**Comment by blkeller** [comment]
Verified.  I no longer get the warning message in the web UI, and I can delete users without issue from both the GUI and the CLI.  Thanks for the super fast fix!

**Comment by kyrofa** [comment]
Excellent, thank you. #419 will get this back into v12 as well.
