### ISSUE TITLE
Change ports tests fail with ruby<2.4

### ISSUE THREAD

**Issue by r4co0n** [nextcloud/nextcloud-snap#463]
With ruby<2.4, as shipped with Ubuntu 16.04, open-uri's open() does [not allow redirection](http://blog.bigbinary.com/2017/03/02/open-uri-in-ruby-2-4-allows-http-to-https-redirection.html) from http->https, thus breaking the following tests:
 * Change ports -> http still redirects to unchanged https (FAILED - 1)
 * Change ports -> http redirects to changed https (FAILED - 2)

A mitigation could be to:
 * Add additional ruby requirement 'open_uri_redirections', which should only contain the [patch](https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/56085) as proposed in this [ruby bug](https://bugs.ruby-lang.org/issues/859).
 * Use some custom [exception catching](https://stackoverflow.com/a/39160567)

```
$ rake test
/usr/bin/ruby2.3 -I/var/lib/gems/2.3.0/gems/rspec-support-3.6.0/lib:/var/lib/gems/2.3.0/gems/rspec-core-3.6.0/lib /var/lib/gems/2.3.0/gems/rspec-core-3.6.0/exe/rspec spec/change_php_memory_limit_spec.rb spec/change_port_spec.rb spec/enable_https_spec.rb spec/login_spec.rb --format documentation

Change PHP memory limit
  unlimited
  bytes
  invalid

Change ports
  http
  https
  http still redirects to unchanged https (FAILED - 1)
  http redirects to changed https (FAILED - 2)

Enabling HTTPS
  self-signed

Logging in
  Logging in with correct credentials
  Loggin in with incorrect credentials

Failures:

  1) Change ports http still redirects to unchanged https
     Failure/Error: output = open(uri, {ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE})
     
     RuntimeError:
       redirection forbidden: http://localhost:81 -> https://localhost/
     # ./spec/spec_helper.rb:191:in `block in wait_for_nextcloud'
     # ./spec/spec_helper.rb:188:in `wait_for_nextcloud'
     # ./spec/change_port_spec.rb:48:in `block (2 levels) in <top (required)>'

  2) Change ports http redirects to changed https
     Failure/Error: output = open(uri, {ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE})
     
     RuntimeError:
       redirection forbidden: http://localhost:81 -> https://localhost:444/
     # ./spec/spec_helper.rb:191:in `block in wait_for_nextcloud'
     # ./spec/spec_helper.rb:188:in `wait_for_nextcloud'
     # ./spec/change_port_spec.rb:61:in `block (2 levels) in <top (required)>'

Finished in 1 minute 40.28 seconds (files took 0.32381 seconds to load)
10 examples, 2 failures

Failed examples:

rspec ./spec/change_port_spec.rb:43 # Change ports http still redirects to unchanged https
rspec ./spec/change_port_spec.rb:56 # Change ports http redirects to changed https

/usr/bin/ruby2.3 -I/var/lib/gems/2.3.0/gems/rspec-support-3.6.0/lib:/var/lib/gems/2.3.0/gems/rspec-core-3.6.0/lib /var/lib/gems/2.3.0/gems/rspec-core-3.6.0/exe/rspec spec/change_php_memory_limit_spec.rb spec/change_port_spec.rb spec/enable_https_spec.rb spec/login_spec.rb --format documentation failed
```

**Comment by kyrofa** [comment]
Yeah I [ran into this in CI](https://github.com/nextcloud/nextcloud-snap/blob/master/.circleci/runtests.sh#L6-L8). Given that I use rvm and CI works now, I agree that this could be better but it's not a high priority for me personally. The 2.4 requirement should be documented in the README, though, sorry for making you figure that out on your own :hugs: .

**Comment by kyrofa** [comment]
I'm going to go ahead and close this. 2.4 is super old now, and .ruby-version should make it pretty clear.
