### ISSUE TITLE
Update to Nextcloud 14

### ISSUE THREAD

**Issue by kristbaum** [nextcloud/nextcloud-snap#706]
As Nextcloud 14 has been released, could we update the beta/stable channels to this release?

**Comment by Mczty** [comment]
try `sudo snap refresh nextcloud --channel=14/beta`

**Comment by kyrofa** [comment]
I like to delay major releases to stable a little bit, but yeah we can get it into the 14 track somewhere.

**Comment by sketchygamesdev** [comment]
Just curious, are there any major issues to consider if I update to the 14/beta from the current stable 13 version?

**Comment by Mczty** [comment]
https://github.com/nextcloud/nextcloud-snap/issues/707
here is the issue i got when updating to 14/beta

**Comment by sketchygamesdev** [comment]
@Mczty I am using the same Ubuntu version that you are and I'm not using a mail server...Has the 14/beta been mostly stable?

**Comment by Mczty** [comment]
it is pretty stable afaik.

**Comment by sketchygamesdev** [comment]
@Mczty Have you been using it consistently or did you revert back to 13?

**Comment by Mczty** [comment]
im still using it.

**Comment by sketchygamesdev** [comment]
thanks. Guess I'll give it a shot.

**Comment by kyrofa** [comment]
`14/candidate` is indeed stable, it only has one bug that causes it to incorrectly display a warning in the admin section, so we're waiting for that to get fixed before we roll it out to everyone. Please do feel free to use it, and let us know if you have any issues! Otherwise, just keep an eye out for when v14 is release to stable, at which time you can refresh back to stable to continue on the upgrade path as normal.

**Comment by matthewrknoll** [comment]
Not sure if this is the error you were referring to, @kyrofa but after doing `sudo snap refresh nextcloud --channel=14/candidate` I'm seeing this:
![image](https://user-images.githubusercontent.com/11138448/46357718-13a0d180-c62b-11e8-91c4-e614d3a60ea7.png)
I can't seem to get either of the errors to go away. Any ideas?

**Comment by Mczty** [comment]
try increase the ram allowance :-)

**Comment by matthewrknoll** [comment]
Thanks so much, @Mczty ! That cleared up the first error. Any idea about this one?:
![image](https://user-images.githubusercontent.com/11138448/46369999-15c65880-c64a-11e8-9822-7cf78e3b3d8a.png)
When I'm in /snap/nextcloud/current/htdocs and I do `sudo php occ db:add-missing-indices` I get "App directory '/snap//current/htdocs/apps' not found! Please put the Nextcloud apps folder in the Nextcloud folder or the folder above. You can also configure the location in the config.php file."

I see where I can add the missing "nexcloud" to the path in the config.php, but I'm not able to write to that file for some reason.

**Comment by Mczty** [comment]
Try `$ sudo nextcloud.occ db:add-missing-indices`

**Comment by matthewrknoll** [comment]
That did it! Thanks, @Mczty 
![image](https://user-images.githubusercontent.com/11138448/46370988-bddd2100-c64c-11e8-9510-f8db0581eb33.png)

**Comment by Mczty** [comment]
Happy to help!

**Comment by PnjDbq** [comment]
> Thanks so much, @Mczty ! That cleared up the first error. Any idea about this one?:
> ![image](https://user-images.githubusercontent.com/11138448/46369999-15c65880-c64a-11e8-9822-7cf78e3b3d8a.png)
> When I'm in /snap/nextcloud/current/htdocs and I do `sudo php occ db:add-missing-indices` I get "App directory '/snap//current/htdocs/apps' not found! Please put the Nextcloud apps folder in the Nextcloud folder or the folder above. You can also configure the location in the config.php file."


I also had this issue after upgrading to 14/candidate.  I gave the system an hour plus a reboot to see if it would index on it's own.  Manually ran `sudo nextcloud.occ db:add-missing-indices` to resolve.  The process completed in under a minute and the setup warning cleared.

**Comment by downeym** [comment]
Thanks to everyone working to get 14 out the door. Looking forward to it!

**Comment by joopy** [comment]
Any update when will 14 be released with snap?

**Comment by KuenzelIT** [comment]
Hey guys,

I'm curious about how you handle updates for this snap. Although nextcloud releases its versions as stable, you still wait to classify it yourself as stable? 

Thanks!

**Comment by KuenzelIT** [comment]
@kyrofa Sounds good. Thank your for the explanation!

**Comment by cortopy** [comment]
@kyrofa that's an amazing answer, but to be honest I would expect the core nextcloud releases to follow the same logic

**Comment by kyrofa** [comment]
That issue has been fixed, and is being backported to v14 here:

https://github.com/nextcloud/server/pull/12529

Looks like it will be in 14.0.4.

**Comment by hombresiniestro** [comment]
> That issue has been fixed, and was backported to v14 [here](https://github.com/nextcloud/server/pull/12529). Looks like it will be in 14.0.4.

It is now in [14.0.4.](https://github.com/nextcloud/server/releases/tag/v14.0.4)

**Comment by kyrofa** [comment]
Anyone who can test #799 would have my undying appreciation.

**Comment by Flaburgan** [comment]
Serious question: is this snap official or is it a hobby project? Even if only volunteers maintain it, Nextcloud 14 has been released for 3 months now. To see the snap not updated makes me worried. If nobody handles updates, what happens when there is a security hotfix release? Looks like I should not have gone the snap way to install my nextcloud.

**Comment by downeym** [comment]
FWIW I asked this question to Frank some weeks back and he suggested it's a fine way to install and stay supported. It is probably not a good choice for folks that want to stay on the "bleeding edge" of updates.

While I too would love to be upgraded to v. 14, there's a clear reason why it's not possible and that bug is being fixed. I personally am not aware of security fixes not rolling out promptly to the snap -- has that been the case?

**Comment by kyrofa** [comment]
Security updates are promptly rolled out. You know you can switch to v14 now by switching to the `14/candidate` channel, right? We haven't moved it to the stable channel for everyone because we haven't been happy with it yet (see #799 for new issues cropping up), but we have a limited amount of time to hack on upstream bugs.

**Comment by MANFahrer-GF** [comment]
Security & setup warnings
It's important for the security and performance of your instance that everything is configured correctly. To help you with that we are doing some automatic checks. Please see the linked documentation for more information.

There are some warnings regarding your setup.
The PHP memory limit is below the recommended value of 512MB.

-14/candidate 
- Ubuntu 18.04

**Comment by brainfrz82** [comment]
I think Nextcloud is way to generous with it's version numbering. Nextcloud 14 and 15 don't include any features that any home user running the snap would use (and I do think corporate users probably should not use the snap). Actually if nextcloud 13 would be supported for a longer time (like a LTS release) i'd be happy to run that version until support expires.

**Comment by Flaburgan** [comment]
@brainfrz82 the performance improvements themselves are enough to justify an upgrade. The difference can really be felt. And I'm personally very excited about the [social features](https://nextcloud.com/blog/nextcloud-introduces-social-features-joins-the-fediverse/) coming with nextcloud 15. But looking at the speed the snap package is updated, I'll probably need to wait a year before seeing it. I will try to find a guide about how to migrate from nextcloud snap to a real nextcloud.

**Comment by brainfrz82** [comment]
@Flaburgan I wasn't aware of noticable performance boost, I don't have any issues with performance on 13, but i do run on a reasonably powered machine. I could see Rpi's or other lower powered machines benefitting from optimization. I'm sure though Nextcloud will be updated before the version is end of life in februari next year.

**Comment by thatscoteng** [comment]
While I generally agree with @brainfrz82, there are a significant number of apps (such as the news app) that are very quick to drop support for the older versions. This is my main reason for wanting to update.

**Comment by downeym** [comment]
Now that 15 is out, can the snap just skip 14 in hopes of catching up? :)

**Comment by kyrofa** [comment]
Unfortunately no, Nextcloud doesn't support skipping major releases, but any bugs we fix for v14 will also get fixed for v15, so the road should hopefully be paved.

**Comment by expressrussian** [comment]
The whole idea of snaps was to speed up and simplify the delivery of applications. When i see this 2-step lag in the roll-out of snap version, i begin to guess that snaps also visualise major development issues. 
The developers start to spread their forces over too many so-called "major" versions instead of finishing one properly. This renders the whole nextcloud thing less desirable.

**Comment by pachulo** [comment]
I'm also in for the new stuff and all that, but staying in a “not so new“ supported branch for a while is not such a big problem for me...but yes, this all comes to show that maybe nextcloud code is not as mature as we all wish, at least to get stable first revisions of new majors...

**Comment by kyrofa** [comment]
Yep, there's a reason we hang back at least a point release or two, and even then (obviously) it's not unusual to find issues that we consider blocking. We're admittedly a bit picky, though.

**Comment by fishscene** [comment]
Just got an email this morning announcing Nextcloud 15 and double-checked that it was available for download - it is.

At this point, the Nextcloud SNAP official stable is now 2 versions behind. I can't help but wonder if we (yes, I'm involving myself) need to evaluate how the SNAP releases are handled or what needs to be done to help speed up the resolution of release-blockers.

In the spirit of trying to help out in some way, I'd like to start a discussion:
It appears the strive for non-buggy releases is strong. This is good. 
However, I'm not sure we will ever have a perfect release. Is there a way we can say something like "New release! Known issues are: x,y - we are working on a fix, don't upgrade if you don't want these issues"?

Or what ideas might y'all have to help keep the SNAP closer to the current Nextcloud release?
:)

**Comment by kyrofa** [comment]
As a reminder to visitors: you can start using v14 today by using the `14/candidate` channel, and use v15 by using the `15/candidate` channel. This issue is for getting v14 to the stable channel for the general populous (it has a few issues holding it back).

**Comment by NightMachinary** [comment]
@kyrofa How can I stay on the latest candidate version automatically?

**Comment by kyrofa** [comment]
The fix for the known blocking issue has landed. While waiting for it to be contained in a release, please take `14/edge` for a spin to make sure there aren't any other issues:

    $ sudo snap install nextcloud --channel=14/edge

Or, if you already have it installed:

    $ sudo snap refresh nextcloud --channel=14/edge

**Comment by kyrofa** [comment]
Y'all ready for this? :musical_note:

**Comment by kyrofa** [comment]
Would love a few folks to test #837 before shipping it.

**Comment by rdao** [comment]
Hi,
My snap tried to upgrade to 14, but failed and remained in maintenance mode. When trying to upgrade by hand I receive these messages:
```$ nextcloud.occ upgrade
The current PHP memory limit is below the recommended value of 512MB.
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Checking for update of app activity in appstore
An unhandled exception has been thrown:
Error: Call to undefined method GuzzleHttp\Client::request() in /snap/nextcloud/10791/htdocs/lib/private/Http/Client/Client.php:161
Stack trace:
#0 /snap/nextcloud/10791/htdocs/lib/private/App/AppStore/Fetcher/Fetcher.php(106): OC\Http\Client\Client->get('https://apps.ne...', Array)
#1 /snap/nextcloud/10791/htdocs/lib/private/App/AppStore/Fetcher/AppFetcher.php(80): OC\App\AppStore\Fetcher\Fetcher->fetch('', '')
#2 /snap/nextcloud/10791/htdocs/lib/private/App/AppStore/Fetcher/Fetcher.php(170): OC\App\AppStore\Fetcher\AppFetcher->fetch('', '')
#3 /snap/nextcloud/10791/htdocs/lib/private/Installer.php(385): OC\App\AppStore\Fetcher\Fetcher->get()
#4 /snap/nextcloud/10791/htdocs/lib/private/Updater.php(440): OC\Installer->isUpdateAvailable('activity')
#5 /snap/nextcloud/10791/htdocs/lib/private/Updater.php(251): OC\Updater->upgradeAppStoreApps(Array)
#6 /snap/nextcloud/10791/htdocs/lib/private/Updater.php(121): OC\Updater->doUpgrade('14.0.5.2', '13.0.8.2')
#7 /snap/nextcloud/10791/htdocs/core/Command/Upgrade.php(258): OC\Updater->upgrade()
#8 /snap/nextcloud/10791/htdocs/3rdparty/symfony/console/Command/Command.php(251): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /snap/nextcloud/10791/htdocs/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /snap/nextcloud/10791/htdocs/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /snap/nextcloud/10791/htdocs/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /snap/nextcloud/10791/htdocs/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /snap/nextcloud/10791/htdocs/console.php(96): OC\Console\Application->run()
#14 /snap/nextcloud/10791/htdocs/occ(11): require_once('/snap/nextcloud...')
```

**Comment by rdao** [comment]
Fixed it following: https://github.com/nextcloud/server/issues/11797
```nextcloud.occ app:disable files_external_gdrive```
