### ISSUE TITLE
php_readline missing;cannot start indexing for fulltextsearch

### ISSUE THREAD

**Issue by anansii** [nextcloud/nextcloud-snap#708]
Hi 

I'm using the latest snap on a Ubuntu 18.4.1 LTS server, trying to setup fulltextsearch-* with elastic search and tesseract for OCR. When I try to start indexing I get the same error as described here:
https://github.com/nextcloud/fulltextsearch/issues/376

The proposed solution is to install php-readline. How can I do that within the snap? I'm guessing I can't, but is there any way to get this up and running?

Thank you

**Comment by ethanfann** [comment]
I am getting the same error as well.

```
An unhandled exception has been thrown:
Error: Call to undefined function OCA\FullTextSearch\Command\readline_callback_handler_install() in /var/snap/nextcloud/8401/nextcloud/extra-apps/fulltextsearch/lib/Command/Live.php:195
Stack trace:
#0 /snap/nextcloud/8401/htdocs/3rdparty/symfony/console/Command/Command.php(251): OCA\FullTextSearch\Command\Live->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /snap/nextcloud/8401/htdocs/core/Command/Base.php(162): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /snap/nextcloud/8401/htdocs/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /snap/nextcloud/8401/htdocs/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FullTextSearch\Command\Live), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /snap/nextcloud/8401/htdocs/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /snap/nextcloud/8401/htdocs/lib/private/Console/Application.php(196): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /snap/nextcloud/8401/htdocs/console.php(90): OC\Console\Application->run()
#7 /snap/nextcloud/8401/htdocs/occ(11): require_once('/snap/nextcloud...')
```

Currently running Nextcloud 14 beta 3 on Ubuntu 18.04 using the snap installation method. Any pointers?

**Comment by kyrofa** [comment]
I commented on #727, but I'll comment here as well. We're not typically willing to introduce new dependencies into the snap unless it's enabling a feature of a built-in app, or we'll be adding all of Ubuntu :stuck_out_tongue: . Finding documentation for how fulltextsearch works is difficult, but I suspect enabling all of its providers will be quite a chore.

**Comment by daita** [comment]
@kyrofa do you want to work on this together to allow your users to index their content ? At least for 15, that should see some better integration within Nextcloud ?

**Comment by kyrofa** [comment]
@daita the line we draw here is simple: we try to make sure we support as fully as possible those apps which Nextcloud ships by default. There's not really any other line we can draw: we can't realistically support every third-party application, as snaps must bundle all their dependencies. If Nextcloud starts shipping indexing apps by default, then we'll enable support for it.

**Comment by sireebob** [comment]
so just to get this straight, from a nextcloud user perspective, the snap of nextcloud simply doesn't support full text search and there's nothing that can be done about it, so if you want it, you have to migrate everything out of the snap and into another mechanism.
is this right?

**Comment by kyrofa** [comment]
Until Nextcloud starts shipping such apps by default, that's correct.

**Comment by sireebob** [comment]
wow, sure wish i would have known how limited the snap was before i wasted so all this time trying to use it. alright then

**Comment by tykayn** [comment]
it looks like it could support elastic search.
i did setup ES outside the snap, installed the ingest-attachement plugin, and when i perform a test it says that the class using ES expects some other parameter.

```bash
$ sudo snap run nextcloud.occ fulltextsearch:test
[sudo] password for tykayn: 
 
.Testing your current setup:  
Creating mocked content provider. ok  
Testing mocked provider: get indexable documents. (2 items) ok  
Loading search platform. (Elasticsearch) ok  
Testing search platform. ok  
Locking process ok  
Removing test. ok  
Pausing 3 seconds 1 2 3 ok  
Initializing index mapping. ok  
Indexing generated documents. ok  
Pausing 3 seconds 1 2 3 ok  
Retreiving content from a big index (license). (size: 32386) ok  
Comparing document with source. ok  
Searching basic keywords:  
 - 'test' An unhandled exception has been thrown:
TypeError: Return value of OCA\FullTextSearch\Model\SearchRequest::getProviders() must be of the type array, null returned in /var/snap/nextcloud/21026/nextcloud/extra-apps/fulltextsearch/lib/Model/SearchRequest.php:114
Stack trace:
#0 /var/snap/nextcloud/21026/nextcloud/extra-apps/fulltextsearch/lib/Model/SearchRequest.php(700): OCA\FullTextSearch\Model\SearchRequest->getProviders()
#1 [internal function]: OCA\FullTextSearch\Model\SearchRequest->jsonSerialize()
#2 /var/snap/nextcloud/21026/nextcloud/extra-apps/fulltextsearch_elasticsearch/lib/Service/SearchService.php(103): json_encode(Object(OCA\FullTextSearch\Model\SearchRequest))
#3 /var/snap/nextcloud/21026/nextcloud/extra-apps/fulltextsearch_elasticsearch/lib/Platform/ElasticSearchPlatform.php(336): OCA\FullTextSearch_ElasticSearch\Service\SearchService->searchRequest(Object(Elasticsearch\Client), Object(OCA\FullTextSearch\Model\SearchResult), Object(OC\FullTextSearch\Model\DocumentAccess))
#4 /var/snap/nextcloud/21026/nextcloud/extra-apps/fulltextsearch/lib/Command/Test.php(584): OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform->searchRequest(Object(OCA\FullTextSearch\Model\SearchResult), Object(OC\FullTextSearch\Model\DocumentAccess))
#5 /var/snap/nextcloud/21026/nextcloud/extra-apps/fulltextsearch/lib/Command/Test.php(436): OCA\FullTextSearch\Command\Test->search(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform), Object(OCA\FullTextSearch\Provider\TestProvider), Object(OC\FullTextSearch\Model\DocumentAccess), 'test', Array)
#6 /var/snap/nextcloud/21026/nextcloud/extra-apps/fulltextsearch/lib/Command/Test.php(171): OCA\FullTextSearch\Command\Test->testSearchSimple(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform), Object(OCA\FullTextSearch\Provider\TestProvider))
#7 /snap/nextcloud/21026/htdocs/3rdparty/symfony/console/Command/Command.php(255): OCA\FullTextSearch\Command\Test->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /snap/nextcloud/21026/htdocs/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /snap/nextcloud/21026/htdocs/3rdparty/symfony/console/Application.php(915): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /snap/nextcloud/21026/htdocs/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FullTextSearch\Command\Test), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /snap/nextcloud/21026/htdocs/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /snap/nextcloud/21026/htdocs/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /snap/nextcloud/21026/htdocs/console.php(99): OC\Console\Application->run()
#14 /snap/nextcloud/21026/htdocs/occ(11): require_once('/snap/nextcloud...')


```
and here is the check command

```
$ sudo snap run nextcloud.occ fulltextsearch:check
Full text search 1.4.1
 
- Search Platform:
Elasticsearch 1.5.1
{
    "elastic_host": [
        "://localhost:9200"
    ],
    "elastic_index": "ncloud",
    "fields_limit": "10000",
    "es_ver_below66": "0",
    "analyzer_tokenizer": "standard"
} 
 
- Content Providers:
Deck 1.0.1
[]
Files 1.4.2
{
    "files_local": "1",
    "files_external": "1",
    "files_group_folders": "1",
    "files_encrypted": "0",
    "files_federated": "0",
    "files_size": "20",
    "files_pdf": "0",
    "files_office": "0",
    "files_image": "0",
    "files_audio": "0"
}

```
