### ISSUE TITLE
User files corrupted, files:scan shows error

### ISSUE THREAD

**Issue by Nutomic** [nextcloud/nextcloud-snap#782]
I am hosting a small Nextcloud instance via Snap for my family. Now one of the users encountered problems, files are missing and uploads are not working. 

I ran the nextcloud.occ command to rescan files, thinking that might fix it. But it actually threw an error for that user. Other users did not show any errors.

```
$ sudo nextcloud.occ files:scan --all

Scanning files for 5 users
Starting scan for user 1 out of 5 (f)
Starting scan for user 2 out of 5 (k)
Exception during scan: Undefined variable: response
#0 /snap/nextcloud/9448/htdocs/lib/private/Files/Storage/DAV.php(283): OCA\Files\Command\Scan->exceptionErrorHandler(8, 'Undefined varia...', '/snap/nextcloud...', 283, Array)
#1 /snap/nextcloud/9448/htdocs/apps/files_sharing/lib/External/Storage.php(355): OC\Files\Storage\DAV->propfind('')                                                                   
#2 /snap/nextcloud/9448/htdocs/lib/private/Files/Storage/Common.php(666): OCA\Files_Sharing\External\Storage->getPermissions('')                                                      
#3 /snap/nextcloud/9448/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php(581): OC\Files\Storage\Common->getMetaData('')                                                           
#4 /snap/nextcloud/9448/htdocs/lib/private/Files/Storage/Wrapper/Availability.php(463): OC\Files\Storage\Wrapper\Wrapper->getMetaData('')                                             
#5 /snap/nextcloud/9448/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php(581): OC\Files\Storage\Wrapper\Availability->getMetaData('')                                             
#6 /snap/nextcloud/9448/htdocs/lib/private/Files/Cache/Scanner.php(112): OC\Files\Storage\Wrapper\Wrapper->getMetaData('')                                                            
#7 /snap/nextcloud/9448/htdocs/lib/private/Files/Cache/Scanner.php(150): OC\Files\Cache\Scanner->getData('')                                                                          
#8 /snap/nextcloud/9448/htdocs/apps/files_sharing/lib/External/Scanner.php(62): OC\Files\Cache\Scanner->scanFile('', true)                                                            
#9 /snap/nextcloud/9448/htdocs/lib/private/Files/Cache/Scanner.php(336): OCA\Files_Sharing\External\Scanner->scanFile('', true, -1, NULL, true)                                       
#10 /snap/nextcloud/9448/htdocs/apps/files_sharing/lib/External/Scanner.php(41): OC\Files\Cache\Scanner->scan('', true, true, true)                                                   
#11 /snap/nextcloud/9448/htdocs/lib/private/Files/Utils/Scanner.php(245): OCA\Files_Sharing\External\Scanner->scan('', true, 3)                                                       
#12 /snap/nextcloud/9448/htdocs/apps/files/lib/Command/Scan.php(172): OC\Files\Utils\Scanner->scan('/k', true, NULL)                                                               
#13 /snap/nextcloud/9448/htdocs/apps/files/lib/Command/Scan.php(249): OCA\Files\Command\Scan->scanFiles('k', '/k', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)                                                                                                                                                                 
#14 /snap/nextcloud/9448/htdocs/3rdparty/symfony/console/Command/Command.php(251): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                                               
#15 /snap/nextcloud/9448/htdocs/core/Command/Base.php(162): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                                                       
#16 /snap/nextcloud/9448/htdocs/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                                                         
#17 /snap/nextcloud/9448/htdocs/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                               
#18 /snap/nextcloud/9448/htdocs/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                                      
#19 /snap/nextcloud/9448/htdocs/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                                             
#20 /snap/nextcloud/9448/htdocs/console.php(96): OC\Console\Application->run()                                                                                                        
#21 /snap/nextcloud/9448/htdocs/occ(11): require_once('/snap/nextcloud...')                                                                                                           
#22 {main}                                                                                                                                                                            
Starting scan for user 3 out of 5 (ma)
Starting scan for user 4 out of 5 (mi)
Starting scan for user 5 out of 5 (s)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 2183    | 61765 | 00:02:25     |
+---------+-------+--------------+
```

**Comment by kyrofa** [comment]
@Nutomic I'm afraid this is more of a Nextcloud question than a snap question, I'm not familiar enough with what's happening there to be of much use to you. I suggest asking in the [Nextcloud forum](https://help.nextcloud.com/).

That said, I'm happy to help you poke around a bit. Do files appear to be missing if you look in that user's data directory? Do you see any errors in the syslog?

**Comment by Nutomic** [comment]
Sorry I wasn't sure where this issue should go.

It seems there is some inconsistency with the files, because the Android app is showing files that don't exist on the server filesystem. Unfortunately I'm in another city so I can't look at that device directly.

I can't see anything relevant in the syslog, also because I don't know when the problem first appeared. The affected username doesn't show up at all. The following line shows up a lot, but I don't know if it's a problem:
```
Nov 14 16:56:43 morpheus kernel: [59011.845932] audit: type=1400 audit(1542211003.774:131): apparmor="DENIED" operation="file_mmap" profile="snap.nextcloud.nextcloud-cron" name="/" pid=27064 comm="php" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
```

**Comment by kyrofa** [comment]
Nah, that denial is fine. Ask in the forum about that trace, I'm not sure what it means.

**Comment by Nutomic** [comment]
Thanks @kyrofa :)

https://help.nextcloud.com/t/user-files-corrupted-files-scan-shows-error/41166
